# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project = "terragrunt-experiment"
  region  = "asia-northeast1"
}
provider "google" {
  alias   = "us-central1"
  project = "terragrunt-experiment"
  region  = "us-central1"
}
